### ISSUE TITLE
AttributeError: module 'smartsheet' has no attribute 'Smartsheet'

### ISSUE THREAD

**Issue by perrinromney** [smartsheet-platform/smartsheet-python-sdk#178]
I am getting the error:

    Traceback (most recent call last):
      File "C:/Users/promney/smartsheet sync with excel/smartsheet.py", line 1, in <module>
        import smartsheet
      File "C:\Users\promney\smartsheet sync with excel\smartsheet.py", line 3, in <module>
        test=smartsheet.Smartsheet()
    AttributeError: module 'smartsheet' has no attribute 'Smartsheet'

I have version 2.105.1 running on Python 3.7.

**Comment by RCoff** [comment]
Hi @perrinromney

It looks like the name of your file 'smartsheet.py' may be creating a conflict.

Try renaming your python file and see if that fixes your issue

**Comment by perrinromney** [comment]
I do love a simple fix. Thanks.
