### ISSUE TITLE
cannot import when using python33 SCL

### ISSUE THREAD

**Issue by rkennedy-ss** [smartsheet-platform/smartsheet-python-sdk#20]
```
$ scl enable python33 python                
Python 3.3.2 (default, Jul 10 2014, 18:29:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smartsheetclient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/smartsheetclient/__init__.py", line 5, in <module>
    from client_1_1 import (
ImportError: No module named 'client_1_1'
```

**Comment by rkennedy-ss** [comment]
after running `2to3`, the diff looked reasonable but I got this import error:

```
$ scl enable python33 python                
Python 3.3.2 (default, Jul 10 2014, 18:29:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smartsheetclient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/smartsheetclient/__init__.py", line 5, in <module>
    from .client_1_1 import (
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/smartsheetclient/client_1_1/__init__.py", line 14, in <module>
    from .client import (HttpRequestInfo, SmartsheetClient, UserProfile, SimpleUser,
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/smartsheetclient/client_1_1/client.py", line 14, in <module>
    import httplib2
  File "/opt/rh/python33/root/usr/lib/python3.3/site-packages/httplib2/__init__.py", line 912
    print "connect: (%s, %s) ************" % (self.host, self.port)
                                         ^
SyntaxError: invalid syntax
```

**Comment by rkennedy-ss** [comment]
I may be building the wrong `httplib2` for the SCL. `httplib2` appears to maintain 2 directories of code named `python2` and `python3`. the one I am building and installing **clearly** has simple python2-isms left.

**Comment by happybob007** [comment]
I have merged in pull request 24 from Ted, which *should* make this work.

**Comment by timwellswa** [comment]
this looks like it was resolved, closing issue.
