### ISSUE TITLE
SSL certificate error not reported as such

### ISSUE THREAD

**Issue by akrherz** [smartsheet-platform/smartsheet-python-sdk#35]
Thank you for your efforts on this library.  I am having troubles getting up and running.  Here's my environment:

* Red Hat 7
* Red Hat supplied python2.7
* Red Hat supplied python-requests 2.6.0
* certifi 2015.11.20.1

A basic request of ```smartsheet.Users.get_current_user()``` results in this cryptic message:
```
Traceback (most recent call last):
  File "ss.py", line 4, in <module>
    print ss.Users.get_current_user()
  File "/usr/lib/python2.7/site-packages/smartsheet/users.py", line 151, in get_current_user
    response = self._base.request(prepped_request, expected, _op)
  File "/usr/lib/python2.7/site-packages/smartsheet/smartsheet.py", line 178, in request
    res = self.request_with_retry(prepped_request, operation)
  File "/usr/lib/python2.7/site-packages/smartsheet/smartsheet.py", line 242, in request_with_retry
    return self._request(prepped_request, operation)
  File "/usr/lib/python2.7/site-packages/smartsheet/smartsheet.py", line 210, in _request
    raise UnexpectedRequestError(rex.request, rex.response)
smartsheet.exceptions.UnexpectedRequestError: (<PreparedRequest [GET]>, None)
```

It turns out that the requests library can't make a simple request to the server:

```
>>> import requests
>>> import certifi
>>> requests.get('https://api.smartsheet.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
>>> requests.get('https://api.smartsheet.com', cert=certifi.where())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL] PEM lib (_ssl.c:2757)
```

 - So it would be nice if the library reported this SSL error as such.

I am also attempting to figure out how to work around this and am puzzled as it does not seem that `certifi` even provides the Symantec certs used by the API server necessary to make this work?  I am missing something obvious about this?  Is there a minimum version requirement on requests? I fully expect I am doing something wrong, so thank you kindly for the help. Thank you!

**Comment by kbrandl** [comment]
Hello and thank you for reaching out -- sorry to hear that you're having trouble.  This library been verified to work with *requests 2.8.1* -- can you try upgrading your requests package to that version?

**Comment by akrherz** [comment]
Thanks for the response, I built current requests master and get the same result.

```
>>> import requests
>>> requests.__version__
'2.9.1'
>>> requests.get('https://api.smartsheet.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
>>> import certifi
>>> requests.get('https://api.smartsheet.com', cert=certifi.where())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL] PEM lib (_ssl.c:2757)
```

I can use `curl` and `wget` without errors on the same system, so shrug.

**Comment by kbrandl** [comment]
We're attempting to repro this issue, and will reach out again as soon as we have info to share.  In the meantime, our apologies for the inconvenience and thank you for your patience.

**Comment by kbrandl** [comment]
Hi and thanks for your patience.  We believe we've identified a resolution for the SSL-related issues with using the SDK on some Linux distributions. Can you please try using version 2015.04.28 of certifi, rather than using the latest version? i.e.,

	pip uninstall certifi
	pip install certifi==2015.04.28

**Comment by akrherz** [comment]
No need to thank me for my patience, I am grateful for the support.  I just hope I don't have you on a massive goose chase...

Sadly, I was not able to make certifi=2015.04.28 work with either requests 2.6.0 nor 2.8.1, I got the same error (_ssl.c:2757) as above

**Comment by akrherz** [comment]
Maybe a more generic question is I assume `certifi` is needed to supply the SSL CA chain for `Symantec Class 3 EV SSL CA - G3`, which signed `api.smartsheet.com`?  Does certifi even do that though?

**Comment by akrherz** [comment]
Hold the presses, this command worked:

```
requests.get('https://api.smartsheet.com', verify=certifi.old_where())
```

**Comment by akrherz** [comment]
Sorry, so this was a quasi goose chase, in my previous day's comments, I was incorrectly using `requests` and specifying a `cert=certifi.where()` instead of `verify=certifi.where()`.

When I downgraded to certifi=2015.04.28, then this works
```
requests.get('https://api.smartsheet.com', verify=certifi.where())
```

So the smartsheet SDK library does work with that version of certifi installed :)

**Comment by kbrandl** [comment]
Excellent.  Glad to hear that; thanks for confirming.

**Comment by cmlccie** [comment]
This doesn't work with:

- requests==2.13.0
- certifi==2015.4.28

``` python
import requests
import certifi
requests.get('https://api.smartsheet.com', verify=certifi.where())
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/chrlunsf/dev/envs/dntt-sync/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/chrlunsf/dev/envs/dntt-sync/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/chrlunsf/dev/envs/dntt-sync/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/chrlunsf/dev/envs/dntt-sync/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/chrlunsf/dev/envs/dntt-sync/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)
```

**Comment by cmlccie** [comment]
This appears to be an issue with the SSL certs being returned by the SmartSheet API server.

**Comment by cmlccie** [comment]
This turned out to be (for me) an issue with the default version of OpenSSL that MacOS ships with.
[https GET request fails with "handshake failure" #2022](https://github.com/kennethreitz/requests/issues/2022)

To resolve, I had to install a newer version of OpenSSL `v1.0.2k` and then reinstall my Python v2 interpreter to have it build using the newer OpenSSL version.  This was easiest to do with Homebrew:

``` bash
brew install openssl
brew install python
```

**Note:**  This issue means that MacOS users will not be able to use this SDK (smartsheet-python-sdk) without jumping through hoops to use an updated OpenSSL library.

_With this issue and the `certifi` package version issues, this package and/or the certificates on the api.smartsheet.com server could really use an update to simplify the use of this SDK._
