### ISSUE TITLE
SSL Certificate Verify Failed

### ISSUE THREAD

**Issue by tberg** [smartsheet-platform/smartsheet-python-sdk#37]
May be related to https://github.com/smartsheet-platform/smartsheet-python-sdk/issues/36.
Debian 8.0, Python 3.4

```
$ cat apitest.py 
#!/usr/bin/env python
import smartsheet
import smartsheet.sheets
import pprint

client = smartsheet.Smartsheet()
sobj = smartsheet.sheets.Sheets(client)
slist = sobj.list_sheets(include_all=True)
pprint.pprint(slist)
```

```
$ python3 apitest.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 577, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/smartsheet/smartsheet.py", line 208, in _request
    res = self._session.send(prepped_request, stream=stream)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apitest.py", line 8, in <module>
    slist = sobj.list_sheets(include_all=True)
  File "/usr/local/lib/python3.4/dist-packages/smartsheet/sheets.py", line 662, in list_sheets
    response = self._base.request(prepped_request, expected, _op)
  File "/usr/local/lib/python3.4/dist-packages/smartsheet/smartsheet.py", line 178, in request
    res = self.request_with_retry(prepped_request, operation)
  File "/usr/local/lib/python3.4/dist-packages/smartsheet/smartsheet.py", line 242, in request_with_retry
    return self._request(prepped_request, operation)
  File "/usr/local/lib/python3.4/dist-packages/smartsheet/smartsheet.py", line 210, in _request
    raise UnexpectedRequestError(rex.request, rex.response)
smartsheet.exceptions.UnexpectedRequestError: (<PreparedRequest [GET]>, None)
```

```
$ pip3 list --local
autopep8 (1.2.1)
Brlapi (0.6.2)
certifi (2015.11.20.1)
chardet (2.3.0)
defer (1.0.6)
devscripts (2.15.1)
docker-compose (1.5.1)
docker-py (1.6.0)
dockerpty (0.3.4)
docopt (0.6.2)
jsonschema (2.5.1)
lazr.uri (1.0.3)
louis (2.5.3)
Magic-file-extensions (0.2)
Mako (1.0.0)
MarkupSafe (0.23)
multi-key-dict (2.0.3)
pbr (1.8.1)
pep8 (1.6.2)
pip (7.1.2)
Pygments (2.0.1)
pygobject (3.14.0)
PyMySQL (0.6.7)
python-apt (0.9.3.11)
python-dateutil (2.4.2)
python-debian (0.1.23)
python-jenkins (0.4.11)
pyxdg (0.25)
PyYAML (3.11)
requests (2.7.0)
requests-toolbelt (0.5.1)
setuptools (19.4)
six (1.10.0)
smartsheet-python-sdk (1.0.1)
texttable (0.8.4)
unattended-upgrades (0.1)
wadllib (1.3.2)
websocket-client (0.34.0)
```

**Comment by kbrandl** [comment]
Hi Ted -- can you please try using version 2015.04.28 of certifi, and see if that resolves this issue?

	pip uninstall certifi
	pip install certifi==2015.04.28

**Comment by SethGoodLuckMartin** [comment]
This issue is similar to #36 

If @kbrandl's solution doesn't solve it try the following: 

`sudo pip install ndg-httpsclient pyasn1 --upgrade`

**Comment by snanda-rh** [comment]
I had the same issue, except on python 2.7.

Downgrading requests resolved it:
`sudo -H pip install requests==2.11.0`

**Comment by SiroosJafary** [comment]
Thanks for that, This is what I get after upgrading the SDK:

`Traceback (most recent call last):
  File "C:/Users/Tony/Desktop/Siroos Python/20170811-Loading Survey to SmartSheet-V2.py", line 119, in <module>
    time_c()
  File "C:/Users/Tony/Desktop/Siroos Python/20170811-Loading Survey to SmartSheet-V2.py", line 118, in time_c
    Updator()
  File "C:/Users/Tony/Desktop/Siroos Python/20170811-Loading Survey to SmartSheet-V2.py", line 22, in Updator
    sheet = smartsheet.Sheets.get_sheet('5683010298242948')
  File "C:\Program Files\Python36\lib\site-packages\smartsheet\sheets.py", line 517, in get_sheet
    response = self._base.request(prepped_request, expected, _op)
  File "C:\Program Files\Python36\lib\site-packages\smartsheet\smartsheet.py", line 242, in request
    res = self.request_with_retry(prepped_request, operation)
  File "C:\Program Files\Python36\lib\site-packages\smartsheet\smartsheet.py", line 333, in request_with_retry
    result = self._request(prepped_request, operation)
  File "C:\Program Files\Python36\lib\site-packages\smartsheet\smartsheet.py", line 304, in _request
    res = self._session.send(prepped_request, stream=stream)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 581, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 417, in send
    timeout=timeout
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 583, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 257, in _get_conn
    return conn or self._new_conn()
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 819, in _new_conn
    strict=self.strict, **self.conn_kw)
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connection.py", line 210, in __init__
    timeout=timeout, **kw)
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connection.py", line 126, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
TypeError: __init__() got an unexpected keyword argument 'ssl_context'

`

**Comment by timwellswa** [comment]
yes, most likely a dependency mismatch. `pip show urllib3` and `pip show requests`. One or both are out of date.

**Comment by SiroosJafary** [comment]
Thanks Tim,

"pip show requests" returns:

`
Name: requests
Version: 2.11.0
Summary: Python HTTP for Humans.
Home-page: http://python-requests.org
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: Apache 2.0
Location: c:\program files\python36\lib\site-packages
Requires:
Required-by: smartsheet-python-sdk, requests-toolbelt
`

and "pip show urllib3" returns:

`PS C:\Windows\system32> pip show urllib3
Name: urllib3
Version: 1.24.1
Summary: HTTP library with thread-safe connection pooling, file post, and more.
Home-page: https://urllib3.readthedocs.io/
Author: Andrey Petrov
Author-email: andrey.petrov@shazow.net
License: MIT
Location: c:\program files\python36\lib\site-packages
Requires:
Required-by:`

But I still get below after running my script:

`Traceback (most recent call last):
  File "C:/Users/Tony/Desktop/Siroos Python/20170811-Loading Survey to SmartSheet-V2.py", line 119, in <module>
    time_c()
  File "C:/Users/Tony/Desktop/Siroos Python/20170811-Loading Survey to SmartSheet-V2.py", line 118, in time_c
    Updator()
  File "C:/Users/Tony/Desktop/Siroos Python/20170811-Loading Survey to SmartSheet-V2.py", line 22, in Updator
    sheet = smartsheet.Sheets.get_sheet('5683010298242948')
  File "C:\Program Files\Python36\lib\site-packages\smartsheet\sheets.py", line 517, in get_sheet
    response = self._base.request(prepped_request, expected, _op)
  File "C:\Program Files\Python36\lib\site-packages\smartsheet\smartsheet.py", line 242, in request
    res = self.request_with_retry(prepped_request, operation)
  File "C:\Program Files\Python36\lib\site-packages\smartsheet\smartsheet.py", line 333, in request_with_retry
    result = self._request(prepped_request, operation)
  File "C:\Program Files\Python36\lib\site-packages\smartsheet\smartsheet.py", line 304, in _request
    res = self._session.send(prepped_request, stream=stream)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 581, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 417, in send
    timeout=timeout
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 583, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 257, in _get_conn
    return conn or self._new_conn()
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 819, in _new_conn
    strict=self.strict, **self.conn_kw)
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connection.py", line 210, in __init__
    timeout=timeout, **kw)
  File "C:\Program Files\Python36\lib\site-packages\requests\packages\urllib3\connection.py", line 126, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
TypeError: __init__() got an unexpected keyword argument 'ssl_context`

**Comment by timwellswa** [comment]
Wow, that requests version is old. Latest is 2.21. I am on 2.19.1. Give updating that a try.

**Comment by SiroosJafary** [comment]
Tim, you solved the issue!

Much appreciated.

**Comment by rulerdo** [comment]
Wow, this article was super helpful, thanks @timwellswa
