### ISSUE TITLE
ValueError: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None

### ISSUE THREAD

**Issue by sbko** [smartsheet-platform/smartsheet-python-sdk#63]
requests==2.17.3
smartsheet-python-sdk==1.2.0
urllib3==1.21.1

```
Traceback (most recent call last):
  File "/var/bdb/tasks/test_smartsheet_api/__init__.py", line 17, in task
    print(ss.Sheets.list_sheets())
  File "/venv/python2713-1/lib/python2.7/site-packages/smartsheet/sheets.py", line 732, in list_sheets
    response = self._base.request(prepped_request, expected, _op)
  File "/venv/python2713-1/lib/python2.7/site-packages/smartsheet/smartsheet.py", line 210, in request
    res = self.request_with_retry(prepped_request, operation)
  File "/venv/python2713-1/lib/python2.7/site-packages/smartsheet/smartsheet.py", line 278, in request_with_retry
    result = self._request(prepped_request, operation)
  File "/venv/python2713-1/lib/python2.7/site-packages/smartsheet/smartsheet.py", line 240, in _request
    res = self._session.send(prepped_request, stream=stream)
  File "/venv/python2713-1/lib/python2.7/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/venv/python2713-1/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/venv/python2713-1/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 587, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/venv/python2713-1/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 302, in _get_timeout
    return Timeout.from_float(timeout)
  File "/venv/python2713-1/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/venv/python2713-1/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/venv/python2713-1/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None.
```

**Comment by seweil** [comment]
@sbko - No one will be able to help without additional information such as your calling code.

Please take a look at the sample project for a starting place: https://github.com/smartsheet-samples/python-read-write-sheet

**Comment by sbko** [comment]
@seweil code:
`
import smartsheet
ss = smartsheet.Smartsheet(access_token)
print(ss.Sheets.list_sheets())
`

**Comment by seweil** [comment]
I've tested on several OSes and versions without problem. 

In urllib3/timeout.py `_validate_timeout()` I'm seeing `value` as `cls.DEFAULT_TIMEOUT` (which is the same as `_GLOBAL_DEFAULT_TIMEOUT`)

You'll have to figure out why this default is being changed in your config.

**Comment by ikeusmaximus** [comment]
Greetings All, I am experiencing the same error with very similar code.  Here is the info

certifi==2018.4.16
chardet==3.0.4
enum34==1.1.6
idna==2.7
python-dateutil==2.7.3
requests==2.19.0
requests-toolbelt==0.8.0
six==1.11.0
smartsheet-python-sdk==1.3.2
urllib3==1.23

python-2.7.5-68.el7.x86_64

import smartsheet
import logging
import sys
ss = smartsheet.Smartsheet(access_token)
sheet = ss.Sheets.get_sheet(sheet_id)

(access_token and sheet_id redacted for security)

After the sheet command I get the same/similar traceback error citing urllib3 timeout.py with the global timeout.  Running the following three commands got the code working on a CentOS server, but not a Red Hat one:

yup update python
pip uninstall -y urllib3 smartsheet-python-sdk requests-toolbelt requests certifi enum34 six python-dateutil idna chardet
pip install -U smartsheet-python-sdk==1.3.2 --no-cache-dir

Essentially this results in a full cache-less re-install, and it is great that it is working for CentOS.  But does anyone have any idea as to how to fix this for Red Hat?
