### ISSUE TITLE
Unable to get sights

### ISSUE THREAD

**Issue by dduransseau** [smartsheet-platform/smartsheet-python-sdk#73]
Unable to retrieve sight object with the Sights.get_sight() method. It seems that the it's not able to parse the 'id' field in the response:

> 
Traceback (most recent call last):
  File "D:/Users/dduransseau/Developpement/trunk/test_script/smartsheet/test1.py", line 59, in <module>
    program_sight = ss.Sights.get_sight(program_sight_id)
  File "C:\Python35\lib\site-packages\smartsheet\sights.py", line 78, in get_sight
    response = self._base.request(prepped_request, expected, _op)
  File "C:\Python35\lib\site-packages\smartsheet\smartsheet.py", line 211, in request
    native = res.native(expected)
  File "C:\Python35\lib\site-packages\smartsheet\smartsheet.py", line 448, in native
    obj = class_(data, self._base)
  File "C:\Python35\lib\site-packages\smartsheet\models\sight.py", line 72, in __init__
    self.widgets = props['widgets']
  File "C:\Python35\lib\site-packages\smartsheet\models\sight.py", line 138, in widgets
    if not isinstance(x, Widget) else x) for x in value
  File "C:\Python35\lib\site-packages\smartsheet\models\sight.py", line 138, in <listcomp>
    if not isinstance(x, Widget) else x) for x in value
  File "C:\Python35\lib\site-packages\smartsheet\models\widget.py", line 98, in __init__
    self.contents = props['contents']
  File "C:\Python35\lib\site-packages\smartsheet\models\widget.py", line 220, in contents
    self._contents = WidgetContent(value, self._base)
  File "C:\Python35\lib\site-packages\smartsheet\models\widget_content.py", line 66, in __init__
    self.hyperlink = props['id']
KeyError: 'id'

>

**Comment by seweil** [comment]
Thanks @dduransseau - we are investigating

**Comment by timwellswa** [comment]
resolved and pulled into master

**Comment by dduransseau** [comment]
Thanks guys
